"""
Seed script -- master data + 52 historical/in-flight PO chains.

Run:  ./.venv/bin/python backend/seed/seed.py [--master-only] [--reset]

Two deliberate design points:

1. MASTER DATA vs TRAFFIC. locations/suppliers/materials/docks/users are
   reference data seeded directly. The PO chains are *historical* traffic --
   also written directly, because they represent things that already happened.
   NEW traffic during a demo is generated by the simulator driving the real
   HTTP APIs, never by touching the database. If the simulator can drive it,
   the system genuinely works.

2. GROUND TRUTH. Every generated pair records the outcome it is SUPPOSED to
   produce into seeds/ground_truth.json. That file is the answer key the eval
   harness scores the 3-way match engine against, which is what turns
   "our match rate is 94%" into a measured number instead of a claimed one.

Historical event_log rows are written with redis_published = TRUE. They are
history that predates the live stream; leaving them FALSE would make
reconcile_unpublished() replay days of old events into a running dashboard.
"""

import argparse
import json
import os
import random
import sys
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from shared.auth import hash_password  # noqa: E402
from shared.db import get_conn  # noqa: E402
from shared.dock_engine import (  # noqa: E402
    DEFAULT_SERVICE_MINUTES,
    Booking,
    DockState,
    TrailerRequest,
    breakdown,
    explain,
    plan_docks,
)
from shared.ids import next_id  # noqa: E402
from shared.match_policy import SEVERITY_BY_TYPE, evaluate  # noqa: E402

SEED = 20260814
random.seed(SEED)

NOW = datetime.now(timezone.utc)
GROUND_TRUTH_PATH = Path(__file__).resolve().parent / "ground_truth.json"


# ─────────────────────────────────────────────
# MASTER DATA
# ─────────────────────────────────────────────

# (id, name, role, email). Email is the login identifier (v5); the service
# account gets None because nobody signs in as it -- shared/auth.py refuses a
# 'system' login even if one were somehow configured.
#
# Every demo account shares DEMO_PASSWORD below. That is a deliberate
# hackathon-demo choice, not an oversight: a judge needs to switch between
# roles in seconds to see the permission model work, and these accounts only
# ever exist in a local seeded database.
USERS = [
    # Service account. Touchless approvals still need a recorded actor --
    # payments.approved_by is a FK to users, and an audit trail that says
    # "approved by nobody" is worse than one naming the autonomous agent.
    ("USR-000", "Autonomous P2P Agent", "system", None),
    ("USR-001", "Priya Raghavan", "operator", "priya@inbound.dev"),
    ("USR-002", "Daniel Okafor", "operator", "daniel@inbound.dev"),
    ("USR-003", "Mei-Ling Chen", "procurement", "meiling@inbound.dev"),
    ("USR-004", "Tomas Alvarez", "procurement", "tomas@inbound.dev"),
    ("USR-005", "Aisha Bakari", "finance", "aisha@inbound.dev"),
    ("USR-006", "Jordan Whitfield", "admin", "jordan@inbound.dev"),
]

DEMO_PASSWORD = os.environ.get("DEMO_PASSWORD", "inbound2026")

# Chicago metro. Real coordinates so the Leaflet map reads as a real network
# rather than random dots; the warehouse is the convergence point.
LOCATIONS = [
    ("LOC-001", "Chicago Distribution Center", "WAREHOUSE", 41.8781, -87.6298),
    ("LOC-002", "Milwaukee Steel Works", "SUPPLIER", 43.0389, -87.9065),
    ("LOC-003", "Gary Industrial Castings", "SUPPLIER", 41.5934, -87.3464),
    ("LOC-004", "Aurora Precision Parts", "SUPPLIER", 41.7606, -88.3201),
    ("LOC-005", "Rockford Tooling Co", "SUPPLIER", 42.2711, -89.0940),
    ("LOC-006", "Kenosha Polymer Supply", "SUPPLIER", 42.5847, -87.8212),
    ("LOC-007", "Joliet Fastener Group", "SUPPLIER", 41.5250, -88.0817),
    ("LOC-008", "South Bend Electronics", "SUPPLIER", 41.6764, -86.2520),
    ("LOC-009", "Madison Composites", "SUPPLIER", 43.0731, -89.4012),
    ("LOC-010", "I-94 Waypoint North", "WAYPOINT", 42.4000, -87.8500),
    ("LOC-011", "I-88 Waypoint West", "WAYPOINT", 41.7800, -88.1000),
    ("LOC-012", "I-90 Waypoint East", "WAYPOINT", 41.6200, -86.9000),
]

# reliability, avg_lead_time_days, quality, risk, price_multiplier
SUPPLIERS = [
    ("SUP-001", "Milwaukee Steel Works", "LOC-002", 0.94, 4, 0.96, 0.06, 1.00),
    ("SUP-002", "Gary Industrial Castings", "LOC-003", 0.88, 3, 0.91, 0.12, 0.94),
    ("SUP-003", "Aurora Precision Parts", "LOC-004", 0.97, 5, 0.98, 0.04, 1.12),
    ("SUP-004", "Rockford Tooling Co", "LOC-005", 0.79, 7, 0.84, 0.24, 0.87),
    ("SUP-005", "Kenosha Polymer Supply", "LOC-006", 0.91, 4, 0.89, 0.10, 0.98),
    ("SUP-006", "Joliet Fastener Group", "LOC-007", 0.85, 2, 0.87, 0.15, 0.91),
    ("SUP-007", "South Bend Electronics", "LOC-008", 0.93, 6, 0.95, 0.08, 1.08),
    ("SUP-008", "Madison Composites", "LOC-009", 0.72, 9, 0.78, 0.31, 0.83),
]

# name, uom, base_price, category, default_supplier
MATERIALS = [
    ("MAT-001", "Industrial Aluminum Tubing", "meter", 12.50, "metals", "SUP-001"),
    ("MAT-002", "Cast Iron Housing Block", "unit", 88.00, "castings", "SUP-002"),
    ("MAT-003", "Precision Ball Bearing 40mm", "unit", 6.75, "precision", "SUP-003"),
    ("MAT-004", "Hardened Steel Die Set", "set", 340.00, "tooling", "SUP-004"),
    ("MAT-005", "HDPE Polymer Pellets", "kg", 2.30, "polymers", "SUP-005"),
    ("MAT-006", "Grade 8 Hex Bolt M12", "unit", 0.42, "fasteners", "SUP-006"),
    ("MAT-007", "PCB Controller Board", "unit", 54.00, "electronics", "SUP-007"),
    ("MAT-008", "Carbon Fibre Sheet 2mm", "sheet", 176.00, "composites", "SUP-008"),
    ("MAT-009", "Stainless Steel Coil 304", "kg", 4.80, "metals", "SUP-001"),
    ("MAT-010", "Aluminium Extrusion Profile", "meter", 9.20, "metals", "SUP-001"),
    ("MAT-011", "Bronze Bushing 25mm", "unit", 3.15, "precision", "SUP-003"),
    ("MAT-012", "Injection Mould Tool", "unit", 1250.00, "tooling", "SUP-004"),
    ("MAT-013", "Silicone Gasket Ring", "unit", 1.10, "polymers", "SUP-005"),
    ("MAT-014", "Wire Harness Assembly", "unit", 27.40, "electronics", "SUP-007"),
    ("MAT-015", "Structural Adhesive 5L", "drum", 96.00, "composites", "SUP-008"),
]

LOAD_TYPES = ["dry_van", "reefer", "flatbed", "tanker"]

# 14 doors, matching the design's D-01..D-14 board. Mixed specialization so the
# dock engine's specialization term has something real to discriminate on, and
# one inactive door so the "Blocked" tile is genuine rather than cosmetic.
DOCKS = [
    ("DOCK-01", ["dry_van"], 1, True, 40),
    ("DOCK-02", ["dry_van", "flatbed"], 2, True, 45),
    ("DOCK-03", ["reefer"], 3, True, 55),
    ("DOCK-04", ["dry_van", "reefer", "flatbed"], 4, True, 50),
    ("DOCK-05", ["dry_van"], 5, True, 40),
    ("DOCK-06", ["tanker"], 6, False, 70),   # inactive -> the "Blocked" tile
    ("DOCK-07", ["flatbed"], 7, True, 60),
    ("DOCK-08", ["dry_van", "reefer"], 8, True, 45),
    ("DOCK-09", ["dry_van"], 9, True, 40),
    ("DOCK-10", ["reefer"], 10, True, 55),
    ("DOCK-11", ["dry_van", "flatbed", "tanker"], 11, True, 50),
    ("DOCK-12", ["dry_van"], 12, True, 40),
    ("DOCK-13", ["flatbed"], 13, True, 60),
    ("DOCK-14", ["dry_van", "reefer"], 14, True, 45),
]

CARRIERS = [
    "Swift Logistics", "J.B. Hunt", "FedEx Freight", "Knight Transportation",
    "Schneider National", "Werner Enterprises", "XPO Logistics", "Old Dominion",
]


def log_event(cur, entity_type, entity_id, event_type, payload, created_at):
    """
    Historical event_log row. redis_published = TRUE on purpose: these events
    predate the live stream, and marking them FALSE would make
    reconcile_unpublished() flood a running dashboard with days of history.
    """
    cur.execute(
        """
        INSERT INTO event_log (entity_type, entity_id, event_type, payload,
                               redis_published, created_at)
        VALUES (%s, %s, %s, %s, TRUE, %s)
        """,
        (entity_type, entity_id, event_type, json.dumps(payload), created_at),
    )


def seed_master(cur):
    # Hash once, not once per user: bcrypt is deliberately slow (~100ms), and
    # seven identical hashes of the same demo password add nothing but delay.
    demo_hash = hash_password(DEMO_PASSWORD)

    for uid, name, role, email in USERS:
        # DO UPDATE, not DO NOTHING, on the credential columns: a database
        # seeded before v5 already has these user rows, so DO NOTHING would
        # leave every demo account permanently unable to log in. Name and role
        # are left alone -- an admin may have re-roled someone since.
        cur.execute(
            """INSERT INTO users (id, name, role, email, password_hash, is_active)
               VALUES (%s,%s,%s,%s,%s,TRUE)
               ON CONFLICT (id) DO UPDATE
                   SET email         = EXCLUDED.email,
                       password_hash = EXCLUDED.password_hash,
                       is_active     = TRUE""",
            (uid, name, role, email, demo_hash if email else None),
        )

    for lid, name, ltype, lat, lon in LOCATIONS:
        cur.execute(
            """INSERT INTO locations (id, name, location_type, latitude, longitude)
               VALUES (%s,%s,%s,%s,%s) ON CONFLICT (id) DO NOTHING""",
            (lid, name, ltype, lat, lon),
        )

    for sid, name, loc, rel, lead, qual, risk, mult in SUPPLIERS:
        cur.execute(
            """INSERT INTO suppliers (id, name, location_id, reliability_score,
                                      avg_lead_time_days, quality_score, risk_score, metadata)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT (id) DO NOTHING""",
            (sid, name, loc, rel, lead, qual, risk, json.dumps({"price_multiplier": mult})),
        )

    for mid, name, uom, price, category, supplier in MATERIALS:
        cur.execute(
            """INSERT INTO materials (id, name, uom, default_supplier_id, metadata)
               VALUES (%s,%s,%s,%s,%s) ON CONFLICT (id) DO NOTHING""",
            (mid, name, uom, supplier, json.dumps({"base_price": price, "category": category})),
        )

    for did, loads, pos, active, unload_min in DOCKS:
        cur.execute(
            """INSERT INTO docks (id, compatible_load_types, yard_position, is_active, metadata)
               VALUES (%s,%s,%s,%s,%s) ON CONFLICT (id) DO NOTHING""",
            (did, loads, pos, active, json.dumps({"expected_unload_minutes": unload_min})),
        )

    print(f"  master data: {len(USERS)} users "
          f"(login: any email below / {DEMO_PASSWORD}), {len(LOCATIONS)} locations, "
          f"{len(SUPPLIERS)} suppliers, {len(MATERIALS)} materials, {len(DOCKS)} docks")


# ─────────────────────────────────────────────
# TRAFFIC
# ─────────────────────────────────────────────

# Lifecycle stage for every chain, so the pipeline funnel and yard board have
# realistic spread instead of everything sitting in one column.
COMPLETE_CHAINS = 26   # reach 3-way matching
IN_FLIGHT = {
    "po_only": 4,        # PO created, nothing shipped
    "en_route": 14,      # trailer moving, ETA within the next two hours
    "arrived": 8,        # at the gate, waiting for a door
    "docked": 5,         # at the door, unloading right now
    "awaiting_exit": 3,  # unloaded, door released, still in the yard
}

# The in-flight mix is sized to CREATE CONTENTION, deliberately. 15 trailers
# (9 en route + 6 waiting at the gate) compete for the 13 active doors, 4 of
# which are already occupied by trailers physically unloading. A yard where
# every truck finds an empty door on arrival cannot demonstrate a scheduling
# decision -- the assignment would be correct and invisible. With this mix the
# optimiser has to sequence trailers into windows, some genuinely wait, and the
# reason strings on the board say why.

# Where each stage sits in time, relative to now. The pre-v6 seeder scattered
# ETAs across a week, which made a "live" yard board show trailers that had
# been due since last Tuesday. A yard operates on a shift; the board has to
# look like one.
STAGE_TIMING_MINUTES = {
    "en_route": (15, 150),        # arriving across the next two and a half hours
    "arrived": (-90, -5),         # rolled through the gate within the last 90 min
    "docked": (-180, -45),        # arrived earlier, at a door now
    "awaiting_exit": (-300, -120),  # unloaded, waiting to clear the gate
}

# The mismatch mix, sized against the chains that ACTUALLY REACH MATCHING --
# a mismatch is only observable on a completed pair, so the 26 complete chains
# are the denominator, not all 40. README §7 asks for 20-30%: this is
# 6 chain-level exceptions + 1 duplicate = 7 of 27 match results = 26%.
#
# `near_miss_qty` is the important one: a 1.5% quantity variance that SHOULD
# approve, proving the tolerance boundary works in both directions rather than
# only that mismatches fail.
#
# `duplicate_invoice` is a clean chain that later receives a SECOND invoice
# against the now-settled PO, so its own match approves and the duplicate is
# what raises the exception -- which is exactly how it happens in reality.
COMPLETE_SCENARIOS = (
    ["clean"] * 18
    + ["near_miss_qty"] * 1
    + ["qty_mismatch"] * 3
    + ["price_mismatch"] * 2
    + ["missing_po"] * 1
    + ["duplicate_invoice"] * 1
)
assert len(COMPLETE_SCENARIOS) == COMPLETE_CHAINS


TOTAL_CHAINS = COMPLETE_CHAINS + sum(IN_FLIGHT.values())


def build_plan():
    """(scenario, stage) for every chain, interleaved so created_at mixes."""
    paired = [(s, "complete") for s in COMPLETE_SCENARIOS]
    for stage, count in IN_FLIGHT.items():
        # In-flight chains have not been invoiced yet, so they carry no
        # mismatch scenario -- there is nothing to mismatch against.
        paired += [("clean", stage)] * count
    assert len(paired) == TOTAL_CHAINS
    random.shuffle(paired)
    return paired


def stage_eta(stage):
    """When this stage's trailer is (or was) due, relative to now."""
    window = STAGE_TIMING_MINUTES.get(stage)
    if window is None:
        return None
    return NOW + timedelta(minutes=random.uniform(*window))


def fetch_docks(cur):
    """Docks as the engine wants them, including the v4 service duration."""
    cur.execute(
        """SELECT id, compatible_load_types, yard_position, is_active,
                  COALESCE((metadata->>'expected_unload_minutes')::numeric, %s)::int
           FROM docks ORDER BY id""",
        (DEFAULT_SERVICE_MINUTES,),
    )
    return [
        DockState(dock_id=r[0], compatible_load_types=list(r[1] or []),
                  yard_position=r[2] or 0, is_active=r[3], service_minutes=r[4])
        for r in cur.fetchall()
    ]


def write_assignment(cur, *, trailer_id, dock_id, status, reason, detail,
                     planned_start, planned_end, assigned_at, docked_at=None):
    """One dock_assignments row, windows included. Returns its id."""
    da_id = next_id(cur, "DA")
    cur.execute(
        """INSERT INTO dock_assignments (id, trailer_id, dock_id, assigned_at, status,
                                         reason, score_breakdown, docked_at,
                                         planned_start, planned_end)
           VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
        (da_id, trailer_id, dock_id, assigned_at, status, reason, json.dumps(detail),
         docked_at, planned_start, planned_end),
    )
    return da_id


def plan_one(docks, trailer_id, load_type, priority, ready_at, bookings_by_dock=None):
    """
    Run the real engine for a single trailer. Used for chains that already
    happened: the door they went to is the door the engine would have chosen,
    so the history on the board is consistent with the logic still running.
    """
    if bookings_by_dock:
        docks = [
            DockState(dock_id=d.dock_id, yard_position=d.yard_position,
                      compatible_load_types=d.compatible_load_types, is_active=d.is_active,
                      service_minutes=d.service_minutes,
                      bookings=list(bookings_by_dock.get(d.dock_id, [])))
            for d in docks
        ]
    request = TrailerRequest(trailer_id=trailer_id, load_type=load_type, priority=priority,
                             ready_at=ready_at)
    plan = plan_docks(docks=docks, trailers=[request], now=ready_at)
    assignment = plan.assignments.get(trailer_id)
    if assignment is None:
        return None, None, None, request
    return plan, assignment, explain(plan, assignment, request), request


def seed_traffic(cur):
    docks = fetch_docks(cur)
    ground_truth = []
    pending = []          # en_route / arrived chains, planned together at the end
    live_bookings = {}    # dock_id -> windows held by trailers already at a door

    for scenario, stage in build_plan():
        # Chain timing runs BACKWARDS from when the trailer is due, for anything
        # still in flight: a truck arriving in 40 minutes was despatched
        # yesterday and requisitioned before that. Deriving t0 forward from a
        # random age instead is what previously produced a "live" yard board
        # full of trailers that had been due for days.
        eta = stage_eta(stage)
        if eta is not None:
            t_ship = eta - timedelta(hours=random.uniform(6, 30))
            t0 = t_ship - timedelta(hours=random.uniform(4, 20))
        else:
            t0 = NOW - timedelta(days=random.uniform(0.2, 7.0))
            t_ship = None

        material = random.choice(MATERIALS)
        mat_id, mat_name, uom, base_price, category, default_supplier = material
        supplier = next(s for s in SUPPLIERS if s[0] == default_supplier)
        sup_id, sup_name, sup_loc, rel, lead, qual, risk, mult = supplier

        qty = Decimal(random.choice([50, 100, 120, 200, 250, 400, 500, 750, 1000]))
        unit_price = (Decimal(str(base_price)) * Decimal(str(mult))).quantize(Decimal("0.01"))

        # --- requisition ---
        req_id = next_id(cur, "REQ")
        requester = random.choice([u[0] for u in USERS if u[2] == "procurement"])
        raw_text = f"We need {qty} {uom} of {mat_name} delivered to the Chicago plant"
        parsed = {
            "material_id": mat_id, "material_name": mat_name, "qty": float(qty),
            "uom": uom, "delivery_location_id": "LOC-001",
            "confidence": round(random.uniform(0.88, 0.99), 3), "ambiguities": [],
            "source": "seed",
        }
        cur.execute(
            """INSERT INTO requisitions (id, requested_by, raw_text, parsed, status, created_at)
               VALUES (%s,%s,%s,%s,%s,%s)""",
            (req_id, requester, raw_text, json.dumps(parsed), "CONVERTED", t0),
        )
        log_event(cur, "requisition", req_id, "REQUISITION_CREATED",
                  {"summary": f"{req_id} raised for {qty} {uom} {mat_name}",
                   "material_id": mat_id, "qty": float(qty)}, t0)

        # --- supplier recommendations (all candidates, not just the winner) ---
        candidates = [s for s in SUPPLIERS if s[0] == sup_id]
        others = [s for s in SUPPLIERS if s[0] != sup_id]
        candidates += random.sample(others, 2)
        scored = []
        for cand in candidates:
            c_id, c_name, _, c_rel, c_lead, c_qual, c_risk, c_mult = cand
            price_score = round(1.0 - min(c_mult - 0.8, 0.4) / 0.4, 3)
            lead_score = round(1.0 - min(c_lead, 10) / 10, 3)
            overall = round(
                0.30 * price_score + 0.25 * c_qual + 0.20 * lead_score
                + 0.15 * c_rel + 0.10 * (1 - c_risk), 3
            )
            scored.append((cand, price_score, lead_score, overall))
        scored.sort(key=lambda x: -x[3])

        for rank, (cand, price_score, lead_score, overall) in enumerate(scored, start=1):
            c_id, c_name, _, c_rel, c_lead, c_qual, c_risk, c_mult = cand
            sr_id = next_id(cur, "SR")
            is_winner = c_id == sup_id
            reasoning = (
                f"{c_name} scores {overall:.2f} overall: quality {c_qual:.2f}, "
                f"reliability {c_rel:.2f}, {c_lead}-day lead time, "
                f"unit price {Decimal(str(base_price)) * Decimal(str(c_mult)):.2f}."
                + (" Selected as best overall fit." if is_winner
                   else " Not selected -- lower combined score.")
            )
            cur.execute(
                """INSERT INTO supplier_recommendations
                   (id, requisition_id, supplier_id, price_score, quality_score,
                    lead_time_score, reliability_score, risk_score, overall_score,
                    rank, recommended, quoted_unit_price, quoted_lead_time_days,
                    reasoning, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
                (sr_id, req_id, c_id, price_score, c_qual, lead_score, c_rel, c_risk,
                 overall, rank, is_winner,
                 (Decimal(str(base_price)) * Decimal(str(c_mult))).quantize(Decimal("0.01")),
                 c_lead, reasoning, t0),
            )
        log_event(cur, "requisition", req_id, "SUPPLIER_RECOMMENDED",
                  {"summary": f"{len(scored)} suppliers scored for {req_id}; "
                              f"{sup_name} recommended",
                   "recommended_supplier_id": sup_id}, t0)

        # --- purchase order ---
        po_id = next_id(cur, "PO")
        expected_delivery = t0 + timedelta(days=lead)
        po_status = "CREATED"
        cur.execute(
            """INSERT INTO purchase_orders
               (id, requisition_id, supplier_id, material_id, qty, unit_price,
                delivery_location_id, expected_delivery, terms, status, created_at, updated_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (po_id, req_id, sup_id, mat_id, qty, unit_price, "LOC-001", expected_delivery,
             json.dumps({"payment_terms": "NET30", "currency": "USD", "incoterm": "DAP"}),
             po_status, t0, t0),
        )
        log_event(cur, "purchase_order", po_id, "PO_CREATED",
                  {"summary": f"{po_id} raised with {sup_name} for {qty} {uom} {mat_name}",
                   "supplier_id": sup_id, "qty": float(qty),
                   "unit_price": float(unit_price)}, t0)

        record = {
            "po_id": po_id, "requisition_id": req_id, "scenario": scenario,
            "stage": stage, "supplier_id": sup_id, "material_id": mat_id,
            "po_qty": float(qty), "po_unit_price": float(unit_price),
        }

        if stage == "po_only":
            ground_truth.append({**record, "expected_match_status": None,
                                 "expected_exception_type": None})
            continue

        # --- shipment ---
        if t_ship is None:                       # historical chain: forwards from t0
            t_ship = t0 + timedelta(hours=random.uniform(4, 20))
            eta = t_ship + timedelta(hours=random.uniform(6, 30))
        shp_id = next_id(cur, "SHP")
        carrier = random.choice(CARRIERS)
        tracking = f"TRK{random.randint(100000, 999999)}"
        shipment_status = {"complete": "UNLOADED", "en_route": "EN_ROUTE",
                           "arrived": "ARRIVED", "docked": "ARRIVED",
                           "awaiting_exit": "UNLOADED"}[stage]
        cur.execute(
            """INSERT INTO shipments (id, po_id, tracking_number, carrier,
                   origin_location_id, destination_location_id, expected_arrival,
                   status, created_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (shp_id, po_id, tracking, carrier, sup_loc, "LOC-001", eta, shipment_status, t_ship),
        )
        cur.execute("UPDATE purchase_orders SET status='SHIPPED', updated_at=%s WHERE id=%s",
                    (t_ship, po_id))
        po_status = "SHIPPED"
        log_event(cur, "shipment", shp_id, "SHIPMENT_CREATED",
                  {"summary": f"{shp_id} despatched by {carrier} for {po_id}",
                   "po_id": po_id, "carrier": carrier, "tracking_number": tracking}, t_ship)

        # --- trailer ---
        trl_id = next_id(cur, "TRL")
        # Tanker is included on purpose and rarely: DOCK-06 (the dedicated
        # tanker door) is out of service, so the only door that can take one is
        # DOCK-11, which also handles dry_van and flatbed. That scarcity is
        # what the flexibility term in the objective exists for, and it is only
        # visible if tankers actually turn up.
        load_type = random.choices(LOAD_TYPES, weights=[6, 3, 3, 1])[0]
        priority = random.choices(["low", "normal", "high", "critical"],
                                  weights=[1, 5, 3, 1])[0]
        trailer_status = {"complete": "DEPARTED", "en_route": "EN_ROUTE",
                          "arrived": "ARRIVED", "docked": "DOCKED",
                          "awaiting_exit": "UNLOADED"}[stage]
        cur.execute(
            """INSERT INTO trailers (id, shipment_id, load_type, priority, eta, status,
                                     created_at, updated_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
            (trl_id, shp_id, load_type, priority, eta, trailer_status, t_ship, t_ship),
        )
        log_event(cur, "trailer", trl_id, "TRAILER_DEPARTED",
                  {"summary": f"{trl_id} departed {sup_name} ({load_type}, {priority} priority)",
                   "shipment_id": shp_id, "load_type": load_type, "priority": priority}, t_ship)

        # --- GPS breadcrumbs ---
        origin = next(loc for loc in LOCATIONS if loc[0] == sup_loc)
        dest = next(loc for loc in LOCATIONS if loc[0] == "LOC-001")
        ticks = {"complete": 8, "en_route": random.randint(3, 6),
                 "arrived": 9, "docked": 9, "awaiting_exit": 9}[stage]
        progress_cap = {"complete": 1.0, "en_route": random.uniform(0.35, 0.8),
                        "arrived": 1.0, "docked": 1.0, "awaiting_exit": 1.0}[stage]
        for i in range(ticks):
            frac = (i + 1) / ticks * progress_cap
            lat = origin[3] + (dest[3] - origin[3]) * frac + random.uniform(-0.02, 0.02)
            lon = origin[4] + (dest[4] - origin[4]) * frac + random.uniform(-0.02, 0.02)
            recorded = t_ship + timedelta(hours=frac * 12)
            cur.execute(
                """INSERT INTO tracking_events (trailer_id, latitude, longitude, speed,
                                                eta_estimate, recorded_at)
                   VALUES (%s,%s,%s,%s,%s,%s)""",
                (trl_id, round(lat, 5), round(lon, 5), round(random.uniform(45, 68), 1),
                 eta, recorded),
            )
        cur.execute("UPDATE trailers SET eta=%s WHERE id=%s", (eta, trl_id))

        # --- dock assignment ---
        #
        # Two different jobs, deliberately handled differently.
        #
        # A trailer that is at a door or has already left is HISTORY: the door
        # it went to is decided one at a time, by the same engine, so the
        # board's history is consistent with the logic still running.
        #
        # A trailer that is still inbound or waiting at the gate is a LIVE
        # SCHEDULING PROBLEM, and scheduling it one chain at a time in seeding
        # order would produce exactly the myopic plan the v6 engine exists to
        # improve on. Those are collected and planned together after the loop.
        t_assign = t_ship + timedelta(minutes=random.uniform(20, 90))
        da_id, docked_at, dock_id = None, None, None

        if stage in ("docked", "awaiting_exit", "complete"):
            if stage == "docked":
                # Recent docked_at so the board shows a live unloading percentage.
                docked_at = NOW - timedelta(minutes=random.uniform(5, 35))
            elif stage == "awaiting_exit":
                docked_at = NOW - timedelta(minutes=random.uniform(75, 150))
            else:
                docked_at = t_assign + timedelta(minutes=random.uniform(30, 120))

            # A trailer at a door occupies it from docked_at, not from whenever
            # the planner would have preferred to start it, so the door has to
            # be genuinely free at that moment. Offering the planner only the
            # free doors is what keeps two trailers from being seeded into one
            # door -- which is not merely untidy, it is a yard state that
            # cannot physically exist.
            candidates = docks
            if stage == "docked":
                candidates = [
                    d for d in docks
                    if not any(b.start < docked_at + timedelta(minutes=d.service_minutes)
                               and docked_at < b.end
                               for b in live_bookings.get(d.dock_id, []))
                ]

            plan, assignment, reason, request = plan_one(
                candidates, trl_id, load_type, priority, docked_at,
                bookings_by_dock=live_bookings if stage == "docked" else None)

            if assignment is None:
                # No active door handles this load at all -- a real yard
                # condition (the tanker door is out of service), recorded the
                # same way the worker records it.
                message = f"no active door handles {load_type} for {trl_id}"
                alt_id = next_id(cur, "ALT")
                cur.execute(
                    """INSERT INTO alerts (id, entity_type, entity_id, alert_type, message,
                                           severity, acknowledged, created_at)
                       VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                    (alt_id, "trailer", trl_id, "DOCK_CONFLICT", message,
                     "warning", False, t_assign),
                )
                log_event(cur, "alert", alt_id, "ALERT_CREATED",
                          {"summary": message, "alert_type": "DOCK_CONFLICT"}, t_assign)
            else:
                dock_id = assignment.dock_id
                service = next(d.service_minutes for d in candidates if d.dock_id == dock_id)
                planned_end = docked_at + timedelta(minutes=service)
                detail = breakdown(plan, assignment, request)
                detail["source"] = "seed"
                da_status = {"docked": "CONFIRMED", "awaiting_exit": "COMPLETED",
                             "complete": "COMPLETED"}[stage]
                da_id = write_assignment(
                    cur, trailer_id=trl_id, dock_id=dock_id, status=da_status,
                    reason=reason, detail=detail, planned_start=docked_at,
                    planned_end=planned_end, assigned_at=t_assign, docked_at=docked_at)
                log_event(cur, "dock_assignment", da_id, "DOCK_ASSIGNED",
                          {"summary": reason, "trailer_id": trl_id, "dock_id": dock_id,
                           "planned_start": docked_at.isoformat(),
                           "planned_end": planned_end.isoformat(),
                           "wait_minutes": assignment.wait_minutes,
                           "cost": assignment.cost}, t_assign)
                if stage == "docked":
                    # This door is genuinely occupied right now, so it is a
                    # fixed booking for everything planned after it.
                    live_bookings.setdefault(dock_id, []).append(
                        Booking(trailer_id=trl_id, start=docked_at, end=planned_end,
                                assignment_id=da_id))

        elif stage in ("en_route", "arrived"):
            pending.append({
                "trailer_id": trl_id, "load_type": load_type, "priority": priority,
                "eta": eta, "stage": stage, "assigned_at": t_assign,
            })

        # --- arrival / docking history ---
        if stage in ("arrived", "docked", "awaiting_exit", "complete"):
            t_arrive = (min(eta, NOW) if stage in ("arrived", "docked", "awaiting_exit")
                        else t_assign + timedelta(minutes=random.uniform(30, 180)))
            log_event(cur, "trailer", trl_id, "TRAILER_ARRIVED",
                      {"summary": f"{trl_id} arrived at the gate", "shipment_id": shp_id},
                      t_arrive)
        if dock_id and stage in ("docked", "awaiting_exit", "complete"):
            log_event(cur, "trailer", trl_id, "TRAILER_DOCKED",
                      {"summary": f"{trl_id} docked at {dock_id}", "dock_id": dock_id},
                      docked_at)

        if stage == "awaiting_exit":
            # Unloaded minutes ago, door released, tractor still in the yard.
            # This is the outbound half of the movement the board now shows.
            t_receipt = docked_at + timedelta(minutes=random.uniform(30, 60))
            gr_id = next_id(cur, "GR")
            cur.execute(
                """INSERT INTO goods_receipts (id, trailer_id, shipment_id, po_id,
                                               qty_received, received_at, verified_by)
                   VALUES (%s,%s,%s,%s,%s,%s,%s)""",
                (gr_id, trl_id, shp_id, po_id, qty, t_receipt, "simulated_cv"),
            )
            cur.execute("UPDATE purchase_orders SET status='RECEIVED', updated_at=%s WHERE id=%s",
                        (t_receipt, po_id))
            cur.execute("UPDATE trailers SET updated_at=%s WHERE id=%s", (t_receipt, trl_id))
            log_event(cur, "goods_receipt", gr_id, "GOODS_RECEIVED",
                      {"summary": f"{gr_id}: {qty} {uom} received against {po_id}",
                       "po_id": po_id, "qty_received": float(qty), "trailer_id": trl_id,
                       "released_dock_id": dock_id}, t_receipt)

        if stage != "complete":
            ground_truth.append({**record, "trailer_id": trl_id, "shipment_id": shp_id,
                                 "expected_match_status": None,
                                 "expected_exception_type": None})
            continue

        # --- goods receipt (E2-owned) ---
        t_receipt = t_assign + timedelta(hours=random.uniform(2, 8))
        qty_received = qty
        gr_id = next_id(cur, "GR")
        cur.execute(
            """INSERT INTO goods_receipts (id, trailer_id, shipment_id, po_id,
                                           qty_received, received_at, verified_by)
               VALUES (%s,%s,%s,%s,%s,%s,%s)""",
            (gr_id, trl_id, shp_id, po_id, qty_received, t_receipt, "simulated_cv"),
        )
        cur.execute("UPDATE shipments SET status='UNLOADED' WHERE id=%s", (shp_id,))
        cur.execute("UPDATE purchase_orders SET status='RECEIVED', updated_at=%s WHERE id=%s",
                    (t_receipt, po_id))
        po_status = "RECEIVED"
        log_event(cur, "goods_receipt", gr_id, "GOODS_RECEIVED",
                  {"summary": f"{gr_id}: {qty_received} {uom} received against {po_id}",
                   "po_id": po_id, "qty_received": float(qty_received),
                   "trailer_id": trl_id, "released_dock_id": dock_id}, t_receipt)

        # The tractor clears the gate an hour or so after unloading. Historical
        # chains end DEPARTED rather than UNLOADED so they leave the yard board
        # instead of accumulating on it forever.
        t_exit = t_receipt + timedelta(minutes=random.uniform(20, 90))
        cur.execute("UPDATE trailers SET updated_at=%s WHERE id=%s", (t_exit, trl_id))
        log_event(cur, "trailer", trl_id, "TRAILER_EXITED",
                  {"summary": f"{trl_id} departed the yard", "shipment_id": shp_id,
                   "trailer_id": trl_id}, t_exit)

        # --- invoice, shaped by the scenario ---
        t_invoice = t_receipt + timedelta(hours=random.uniform(1, 30))
        inv_qty, inv_price, inv_po = qty_received, unit_price, po_id

        if scenario == "qty_mismatch":
            inv_qty = (qty_received * Decimal(random.choice(["1.10", "1.08", "0.90", "1.15"]))
                       ).quantize(Decimal("0.01"))
        elif scenario == "near_miss_qty":
            inv_qty = (qty_received * Decimal("1.015")).quantize(Decimal("0.01"))
        elif scenario == "price_mismatch":
            inv_price = (unit_price * Decimal(random.choice(["1.06", "1.09", "0.92", "1.12"]))
                         ).quantize(Decimal("0.01"))
        elif scenario == "missing_po":
            inv_po = None

        tax = (inv_qty * inv_price * Decimal("0.08")).quantize(Decimal("0.01"))
        total = (inv_qty * inv_price + tax).quantize(Decimal("0.01"))
        inv_id = next_id(cur, "INV")
        confidence = round(random.uniform(0.91, 0.995), 3)
        cur.execute(
            """INSERT INTO invoices (id, po_id, qty_invoiced, unit_price_invoiced, tax,
                                     total, ocr_confidence, ocr_raw, received_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (inv_id, inv_po, inv_qty, inv_price, tax, total, confidence,
             json.dumps({
                 "vendor": sup_name, "po_reference": inv_po,
                 "field_confidence": {
                     "supplier_name": round(random.uniform(0.95, 0.999), 3),
                     "po_reference": 0.0 if inv_po is None else round(random.uniform(0.9, 0.99), 3),
                     "qty_invoiced": round(random.uniform(0.92, 0.99), 3),
                     "unit_price_invoiced": round(random.uniform(0.92, 0.99), 3),
                     "total": round(random.uniform(0.97, 0.999), 3),
                 },
                 "engine": "seed",
             }), t_invoice),
        )
        log_event(cur, "invoice", inv_id, "INVOICE_RECEIVED",
                  {"summary": f"{inv_id} received from {sup_name} "
                              f"({inv_qty} @ {inv_price})",
                   "po_id": inv_po, "total": float(total)}, t_invoice)
        log_event(cur, "invoice", inv_id, "OCR_COMPLETED",
                  {"summary": f"OCR extracted {inv_id} at {confidence:.1%} confidence",
                   "ocr_confidence": confidence}, t_invoice)

        # --- 3-way match, via the real locked policy ---
        decision_m = evaluate(
            po_id=inv_po, po_status=po_status, po_qty=qty, po_unit_price=unit_price,
            qty_received=qty_received, qty_invoiced=inv_qty,
            unit_price_invoiced=inv_price,
        )
        t_match = t_invoice + timedelta(minutes=random.uniform(1, 10))
        mr_id = next_id(cur, "MR")
        cur.execute(
            """INSERT INTO match_results (id, po_id, goods_receipt_id, invoice_id,
                                          status, reason, created_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s)""",
            (mr_id, inv_po, gr_id, inv_id, decision_m.status, decision_m.reason, t_match),
        )
        log_event(cur, "match_result", mr_id, "MATCH_COMPLETED",
                  {"summary": f"{mr_id}: {decision_m.status} -- {decision_m.reason}",
                   "po_id": inv_po, "invoice_id": inv_id,
                   "status": decision_m.status}, t_match)

        if decision_m.approved:
            pay_id = next_id(cur, "PAY")
            paid = random.random() < 0.6
            cur.execute(
                """INSERT INTO payments (id, invoice_id, amount, status, approved_by,
                                         approved_at, paid_at, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                (pay_id, inv_id, total, "PAID" if paid else "APPROVED", "USR-005",
                 t_match, t_match + timedelta(days=1) if paid else None, t_match),
            )
            cur.execute(
                "UPDATE purchase_orders SET status=%s, updated_at=%s WHERE id=%s",
                ("CLOSED" if paid else "MATCHED", t_match, po_id),
            )
            log_event(cur, "payment", pay_id, "PAYMENT_APPROVED",
                      {"summary": f"{pay_id} approved for {total} against {inv_id}",
                       "invoice_id": inv_id, "amount": float(total)}, t_match)
            if paid:
                log_event(cur, "payment", pay_id, "PAYMENT_PAID",
                          {"summary": f"{pay_id} paid ({total})", "amount": float(total)},
                          t_match + timedelta(days=1))
        else:
            exc_id = next_id(cur, "EXC")
            assignee = random.choice([u[0] for u in USERS if u[2] in ("procurement", "finance")])
            cur.execute(
                """INSERT INTO exceptions (id, match_result_id, exception_type, status,
                                           assigned_to, severity, impact_amount, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                (exc_id, mr_id, decision_m.exception_type, "OPEN", assignee,
                 decision_m.severity or SEVERITY_BY_TYPE.get(decision_m.exception_type, "medium"),
                 decision_m.impact_amount, t_match),
            )
            log_event(cur, "exception", exc_id, "EXCEPTION_CREATED",
                      {"summary": f"{exc_id}: {decision_m.exception_type} on "
                                  f"{inv_po or 'unmatched invoice'} -- {decision_m.reason}",
                       "exception_type": decision_m.exception_type,
                       "severity": decision_m.severity,
                       "impact_amount": float(decision_m.impact_amount or 0)}, t_match)

        # --- duplicate invoice: a SECOND invoice against a now-settled PO ---
        if scenario == "duplicate_invoice":
            cur.execute("SELECT status FROM purchase_orders WHERE id=%s", (po_id,))
            settled_status = cur.fetchone()[0]
            t_dup = t_match + timedelta(hours=random.uniform(2, 24))
            dup_id = next_id(cur, "INV")
            cur.execute(
                """INSERT INTO invoices (id, po_id, qty_invoiced, unit_price_invoiced, tax,
                                         total, ocr_confidence, ocr_raw, received_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
                (dup_id, po_id, inv_qty, inv_price, tax, total, confidence,
                 json.dumps({"vendor": sup_name, "po_reference": po_id, "engine": "seed",
                             "note": "resubmission"}), t_dup),
            )
            log_event(cur, "invoice", dup_id, "INVOICE_RECEIVED",
                      {"summary": f"{dup_id} received from {sup_name} (resubmission)",
                       "po_id": po_id, "total": float(total)}, t_dup)
            dup_decision = evaluate(
                po_id=po_id, po_status=settled_status, po_qty=qty, po_unit_price=unit_price,
                qty_received=qty_received, qty_invoiced=inv_qty,
                unit_price_invoiced=inv_price,
            )
            dup_mr = next_id(cur, "MR")
            cur.execute(
                """INSERT INTO match_results (id, po_id, goods_receipt_id, invoice_id,
                                              status, reason, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s)""",
                (dup_mr, po_id, gr_id, dup_id, dup_decision.status, dup_decision.reason, t_dup),
            )
            dup_exc = next_id(cur, "EXC")
            cur.execute(
                """INSERT INTO exceptions (id, match_result_id, exception_type, status,
                                           assigned_to, severity, impact_amount, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                (dup_exc, dup_mr, dup_decision.exception_type, "OPEN", "USR-005",
                 dup_decision.severity, total, t_dup),
            )
            log_event(cur, "exception", dup_exc, "EXCEPTION_CREATED",
                      {"summary": f"{dup_exc}: DUPLICATE_INVOICE on {po_id} -- "
                                  f"{dup_decision.reason}",
                       "exception_type": dup_decision.exception_type,
                       "severity": dup_decision.severity}, t_dup)
            record["duplicate_invoice_id"] = dup_id

        ground_truth.append({
            **record,
            "trailer_id": trl_id, "shipment_id": shp_id, "goods_receipt_id": gr_id,
            "invoice_id": inv_id, "match_result_id": mr_id,
            "qty_received": float(qty_received), "qty_invoiced": float(inv_qty),
            "unit_price_invoiced": float(inv_price),
            "expected_match_status": decision_m.status,
            "expected_exception_type": decision_m.exception_type,
        })

    schedule_pending(cur, docks, pending, live_bookings)
    return ground_truth


def schedule_pending(cur, docks, pending, live_bookings):
    """
    Plan every inbound and waiting trailer in ONE optimisation, exactly as
    dock-worker does at runtime.

    This is the difference the seed has to show. Scheduling each trailer as it
    is generated gives the first trailer in the list the best door and leaves
    the last one whatever is left; planning them jointly sequences them into
    windows, so the seeded board opens on a yard where doors are shared over
    time, some trailers are queued behind others, and every reason string on
    screen was produced by the same solver that will run during the demo.
    """
    if not pending:
        return

    docks_with_bookings = [
        DockState(dock_id=d.dock_id, yard_position=d.yard_position,
                  compatible_load_types=d.compatible_load_types, is_active=d.is_active,
                  service_minutes=d.service_minutes,
                  bookings=list(live_bookings.get(d.dock_id, [])))
        for d in docks
    ]
    requests = [
        TrailerRequest(
            trailer_id=p["trailer_id"], load_type=p["load_type"], priority=p["priority"],
            # A trailer already at the gate is ready now; one still inbound is
            # ready when it gets here.
            ready_at=NOW if p["stage"] == "arrived" else max(p["eta"], NOW),
        )
        for p in pending
    ]
    plan = plan_docks(docks=docks_with_bookings, trailers=requests, now=NOW)
    by_id = {r.trailer_id: r for r in requests}
    stages = {p["trailer_id"]: p for p in pending}

    waits = []
    for trailer_id, assignment in sorted(plan.assignments.items()):
        request = by_id[trailer_id]
        detail = breakdown(plan, assignment, request)
        detail["source"] = "seed"
        reason = explain(plan, assignment, request)
        da_id = write_assignment(
            cur, trailer_id=trailer_id, dock_id=assignment.dock_id, status="ASSIGNED",
            reason=reason, detail=detail, planned_start=assignment.start,
            planned_end=assignment.end, assigned_at=stages[trailer_id]["assigned_at"])
        log_event(cur, "dock_assignment", da_id, "DOCK_ASSIGNED",
                  {"summary": reason, "trailer_id": trailer_id,
                   "dock_id": assignment.dock_id,
                   "planned_start": assignment.start.isoformat(),
                   "planned_end": assignment.end.isoformat(),
                   "wait_minutes": assignment.wait_minutes, "cost": assignment.cost},
                  stages[trailer_id]["assigned_at"])
        waits.append(assignment.wait_minutes)

        if assignment.wait_minutes >= 45:
            message = (f"{trailer_id} waits {assignment.wait_minutes} min "
                       f"for {assignment.dock_id}")
            alt_id = next_id(cur, "ALT")
            cur.execute(
                """INSERT INTO alerts (id, entity_type, entity_id, alert_type, message,
                                       severity, acknowledged, created_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                (alt_id, "dock_assignment", da_id, "DELAY", message,
                 "critical" if assignment.wait_minutes >= 120 else "warning", False, NOW),
            )
            log_event(cur, "dock_assignment", da_id, "DOCK_DELAYED",
                      {"summary": message, "trailer_id": trailer_id,
                       "dock_id": assignment.dock_id,
                       "wait_minutes": assignment.wait_minutes,
                       "planned_start": assignment.start.isoformat(),
                       "alert_type": "DELAY"}, NOW)

    for stuck in plan.unplaceable:
        alt_id = next_id(cur, "ALT")
        cur.execute(
            """INSERT INTO alerts (id, entity_type, entity_id, alert_type, message,
                                   severity, acknowledged, created_at)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
            (alt_id, "trailer", stuck.trailer_id, "DOCK_CONFLICT", stuck.reason,
             "warning", False, NOW),
        )
        log_event(cur, "alert", alt_id, "ALERT_CREATED",
                  {"summary": stuck.reason, "alert_type": "DOCK_CONFLICT",
                   "trailer_id": stuck.trailer_id}, NOW)

    print(f"  scheduled {len(plan.assignments)} inbound trailers via {plan.engine} "
          f"({plan.status}): plan cost {plan.total_cost} vs {plan.greedy_cost} greedy, "
          f"{sum(1 for w in waits if w)} queued, "
          f"longest wait {max(waits) if waits else 0} min, "
          f"{len(plan.unplaceable)} unplaceable")


def reset(cur):
    """Truncate every table and restart the ID sequences."""
    cur.execute("""
        TRUNCATE processed_events, audit_logs, event_log, alerts, payments, exceptions,
                 match_results, invoices, goods_receipts, dock_assignments, tracking_events,
                 trailers, shipments, purchase_orders, supplier_recommendations,
                 requisitions, docks, materials, suppliers, locations, users
        RESTART IDENTITY CASCADE
    """)
    for seq in ("requisition_id_seq", "supplier_recommendation_id_seq", "purchase_order_id_seq",
                "shipment_id_seq", "trailer_id_seq", "dock_assignment_id_seq",
                "goods_receipt_id_seq", "invoice_id_seq", "match_result_id_seq",
                "exception_id_seq", "payment_id_seq", "alert_id_seq"):
        cur.execute(f"ALTER SEQUENCE {seq} RESTART WITH 1001")


def main():
    ap = argparse.ArgumentParser(description="Seed the Inbound-to-Pay database.")
    ap.add_argument("--master-only", action="store_true", help="reference data only, no traffic")
    ap.add_argument("--reset", action="store_true", help="truncate everything first")
    args = ap.parse_args()

    with get_conn() as conn:
        with conn.cursor() as cur:
            if args.reset:
                print("• resetting all tables")
                reset(cur)

            print("• seeding master data")
            seed_master(cur)

            ground_truth = []
            if not args.master_only:
                print(f"• seeding {TOTAL_CHAINS} PO chains")
                ground_truth = seed_traffic(cur)

        conn.commit()

    if ground_truth:
        GROUND_TRUTH_PATH.write_text(json.dumps({
            "seed": SEED,
            "generated_at": NOW.isoformat(),
            "chains": ground_truth,
        }, indent=2))
        matched = [g for g in ground_truth if g["expected_match_status"]]
        exceptions = [g for g in matched if g["expected_match_status"] == "EXCEPTION"]
        print(f"  {len(ground_truth)} chains ({len(matched)} reached matching, "
              f"{len(exceptions)} expected exceptions "
              f"= {len(exceptions)/max(len(matched),1):.0%} of matched)")
        print(f"  ground truth -> {GROUND_TRUTH_PATH}")

    print("done.")


if __name__ == "__main__":
    main()
